# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: Anhdat123.
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: rails_tutorial
  
test:
  <<: *default
  database: rails_tutorial_test
  
production:
  <<: *default
  database: rails_tutorial_production
  username: anhdat123exx
  password: <%= ENV['LOGIN_APP_DATABASE_PASSWORD'] %>